# Generated by Django 3.0.5 on 2020-05-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('username', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('S', 'Unspecified')], max_length=1)),
                ('age', models.IntegerField(null=True)),
                ('address', models.TextField()),
                ('bloodgroup', models.CharField(max_length=5)),
                ('password', models.CharField(max_length=32)),
                ('conformpass', models.CharField(max_length=15)),
            ],
        ),
    ]
